---
title: "individual_unique_diagnoses_by_date"
output: html_document
editor_options: 
  chunk_output_type: inline
---

# Individual unique diagnoses, outpatient naive
## Data wrangling 
Common base
### Base dataframes
```{r}
df_outpatient_most_severe <- df_outpatient_preprocessed %>%
  recode_with_most_severe_diagnosis_for_sequence(dw_sk_lpr3forloebsansvar) %>% 
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)
```

```{r}
df_outpatient_last_visit_only <- df_outpatient_preprocessed %>%
  recode_diagnoses_with_last_in_sequence(dw_sk_lpr3forloebsansvar) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)
```

```{r}
df_outpatient_naive_summarised <- df_outpatient_preprocessed %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = TRUE)
```

```{r}
log_time()

```

### Truncation df
```{r}
df_truncation <- df_outpatient_unmitigated %>%
  filter(period > ymd("2012-12-31")) %>%
  pivot_longer(
    cols = c(
      mean_1, mean_2, mean_3, mean_4,
      lcl_1, lcl_2, lcl_3, lcl_4,
      ucl_1, ucl_2, ucl_3, ucl_4
    ),
    names_to = "unit_length"
  ) %>%
  separate(unit_length, into = c("unit", "truncation"), sep = "_") %>%
  pivot_wider(
    names_from = unit,
    values_from = value
  ) %>%
  mutate(truncation = case_when(
    truncation == 1 ~ "FX",
    truncation == 2 ~ "FXX",
    truncation == 3 ~ "FXX.X",
    truncation == 4 ~ "FXX.XX"
  ))

write_csv(df_truncation, here("csv", "df_truncation.csv"))
```

## Plotting
### Mitigation (plot)
```{r}
source(here("src", "functions.r"))

df_mitigation_without_first_quarters <- create_mitigation_df(
  df_default = df_outpatient_unmitigated,
  df_most_severe = df_outpatient_most_severe,
  df_last_visit_only = df_outpatient_last_visit_only
)

write_csv(df_mitigation_without_first_quarters, here("csv", "df_mitigation_without_first_quarters.csv"))
```

```{r}
df_mitigation_without_first_quarters <- read_csv(here("csv", "df_mitigation_without_first_quarters.csv"))
  
pacman::p_load(
  fable, 
  tsibble, 
  feasts, 
  urca
)

## What to report?
## pdq(0,0,0) = linear model / z.test (no detrending)
## pdq(0,1,0) = liear model with differencing
## pdq(1,1,0) = autoregressive model with differencing

df_mitigation_without_first_quarters_p_values <- df_mitigation_without_first_quarters %>%
  mutate(lpr3 = if_else(period < "2019-02-03", 0, 1)) %>% 
  mutate(period = yearquarter(period)) %>%
  select(mean_2, period, origin, lpr3) %>%
  as_tsibble(key = origin, index = period) %>%
  model(arima = ARIMA(mean_2 ~ 1 + lpr3 + pdq(0, 0, 0) + PDQ(0, 0, 0))) %>%
  coef() %>%
  select(!.model) %>%
  filter(term == "lpr3") %>%
  ungroup() %>%
  mutate(
    corrected_p = p.adjust(p.value, "fdr", n = 70), # 3 comparisons
    significant = if_else(corrected_p < 0.05, "*", "")
  )

df_mitigation_without_first_quarters_p_values <- df_mitigation_without_first_quarters %>%
   filter(period == max(period)) %>%
   select(period, mean_2, origin) %>%
   left_join(df_mitigation_without_first_quarters_p_values, by = "origin")
```


```{r}
p <- save_mitigation_strategy_plot(
  df_mitigation_without_first_quarters,
  filename = "examine_mitigation_individual_unique_diagnoses_by_quarter_p_values",
  p_values = df_mitigation_without_first_quarters_p_values,
  nudge_constant = 0.001,
  exclusive_column_for_lpr2 = "Unmitigated"
)

p
```

### Truncation (plot)
```{r}
df_truncation <- read_csv(here("csv", "df_truncation.csv"))

## binary indicator for date in LPR2/LPR3
df_truncation <- df_truncation %>%
  mutate(lpr3 = if_else(period < "2019-02-03", 0, 1))

## What to report?
## pdq(0,0,0) = linear model / z.test (no detrending)
## pdq(0,1,0) = liear model with differencing
## pdq(1,1,0) = autoregressive model with differencing
df_truncation_p_values <- df_truncation %>%
  mutate(period = yearquarter(period)) %>%
  as_tsibble(key = truncation, index = period) %>%
  model(arima = ARIMA(mean ~ 1 + lpr3 + pdq(1, 1, 0) + PDQ(0, 0, 0))) %>%
  coef() %>%
  select(!.model) %>%
  filter(term == "lpr3") %>%
  mutate(
    corrected_p = p.adjust(p.value, "fdr", n = 70), # 4 comparisons
    significant = if_else(corrected_p < 0.05, "*", "")
  )


df_truncation_p_values <- df_truncation %>%
  mutate(period = as.Date(period)) %>%
  filter(period == max(period)) %>%
  select(period, mean, truncation) %>%
  left_join(df_truncation_p_values, by = "truncation")


df_truncation_p_values
```

```{r}
truncation_plot <- save_truncation_plot(df_truncation,
  "examine_truncation_individual_unique_diagnoses_by_quarter_p_values",
  p_values = df_truncation_p_values
)

truncation_plot
```

### Combined
```{r}
combined <- save_combined_plots(truncation_plot, p, "combined_naive_individual_unique_diagnoses_with_p_values")

combined
```