---
title: "individual_unique_diagnoses_by_date"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r}
source(here("rmd", "individual_unique_diagnoses", "0_setup_env_unique_diagnoses.r"))
```

# Individual unique diagnoses, outpatient constructed
## Data wrangling 
### Base pre-processing
```{r}
source(here("src", "functions.r"))
```

## 3m threshold
### Construct sequences and save
```{r}
source(here("src", "functions.r"))

df_outpatient_constructed_3m_threshold <- df_outpatient_preprocessed %>%
  construct_sequences(
    clinic_id_col = shakafskode_besoeg,
    patient_id_col = dw_ek_borger,
    date_col = datotid_start,
    threshold_months = 3,
    verbose = TRUE
  )

write_csv(df_outpatient_constructed_no_threshold, here("csv", "df_outpatient_constructed_3m_threshold.csv"))
```


## No threshold
### Construct sequences
```{r}
source(here("src", "functions.r"))

df_outpatient_constructed_no_threshold <- df_outpatient_preprocessed %>%
  construct_sequences(
    clinic_id_col = shakafskode_besoeg,
    patient_id_col = dw_ek_borger,
    date_col = datotid_start,
    threshold_months = 0,
    verbose = TRUE
  )

write_csv(df_outpatient_constructed_no_threshold, here("csv", "df_outpatient_constructed_no_threshold.csv"))
```

```{r}
source(here("src", "functions.r"))
```

```{r no_threshold_default}
df_outpatient_constructed_no_threshold_default <- df_outpatient_constructed_no_threshold %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

write_csv(df_outpatient_constructed_no_threshold_default, here("csv", "df_outpatient_constructed_no_threshold_default.csv"))
```

```{r most_severe}
df_outpatient_constructed_no_threshold_most_severe <- df_outpatient_constructed_no_threshold %>%
  recode_with_most_severe_diagnosis_for_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

write_csv(df_outpatient_constructed_no_threshold_default, here("csv", "df_outpatient_constructed_no_threshold_most_severe.csv"))
```

```{r last_visit_only}
df_outpatient_constructed_no_threshold_last_visit_only <- df_outpatient_constructed_no_threshold %>%
  recode_diagnoses_with_last_in_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

write_csv(df_outpatient_constructed_no_threshold_default, here("csv", "df_outpatient_constructed_no_threshold_last_visit_only.csv"))

log_time()
```

### Plotting
```{r fig.height=5, fig.width=10}
log_time()
source(here("src", "individual_unique_diagnoses_functions.r"))
source(here("src", "functions.r"))

df_mitigation_constructed_no_threshold_plot <- create_mitigation_df(
  df_default = df_outpatient_constructed_no_threshold_default,
  df_most_severe = df_outpatient_constructed_no_threshold_most_severe,
  df_last_visit_only = df_outpatient_constructed_no_threshold_last_visit_only
)

write_csv(df_mitigation_constructed_no_threshold_plot, here("csv", "df_mitigation_constructed_no_threshold_plot.csv"))
```

```{r}
df_mitigation_constructed_no_threshold_plot <- read_csv(here("csv", "df_mitigation_constructed_no_threshold_plot.csv"))
mitigation_constructed_no_threshold_plot <- save_mitigation_strategy_plot(df_mitigation_constructed_no_threshold_plot,
                                                                          "mitigation_constructed_no_threshold",
                                                                          exclusive_column_for_lpr2 = "Unmitigated")

mitigation_constructed_no_threshold_plot
```


## Plots with P-values
### Mitigation, no threshold
```{r}
source(here("src", "functions.r"))
df_mitigation <- create_mitigation_df(
  df_default = df_outpatient_constructed_no_threshold_default,
  df_most_severe = df_outpatient_constructed_no_threshold_most_severe,
  df_last_visit_only = df_outpatient_constructed_no_threshold_last_visit_only
)

write_csv(df_mitigation, here("csv", "df_mitigation_outpatient_constructed.csv"))
```

```{r}
df_mitigation <- read_csv(here("csv", "df_mitigation_outpatient_constructed.csv"))
pacman::p_load(fable, tsibble, feasts, urca)

## Binary indicator for date in LPR2/LPR3
df_mitigation <- df_mitigation %>%
  mutate(lpr3 = if_else(period < "2019-02-03", 0, 1))
```

```{r}
## What to report?
## pdq(0,0,0) = linear model / t.test (no detrending)
## pdq(0,1,0) = liear model with differencing
## pdq(1,1,0) = autoregressive model with differencing
df_mitigation_p_values <- df_mitigation %>%
  mutate(period = yearquarter(period)) %>%
  select(mean_2, period, origin, lpr3) %>%
  as_tsibble(key = origin, index = period) %>%
  model(arima = ARIMA(mean_2 ~ 1 + lpr3 + pdq(0, 0, 0) + PDQ(0, 0, 0))) %>%
  coef() %>%
  select(!.model) %>%
  filter(term == "lpr3") %>%
  ungroup() %>%
  mutate(
    corrected_p = p.adjust(p.value, "fdr", n = 70), # 3 comparisons
    significant = if_else(corrected_p < 0.05, "*", "")
  )
```

```{r}
df_mitigation_p_values <- df_mitigation %>%
  filter(period == max(period)) %>%
  select(period, mean_2, origin) %>%
  left_join(df_mitigation_p_values, by = "origin")

df_mitigation_p_values
```

```{r}
source(here("src", "individual_unique_diagnoses_functions.r"))

p <- save_mitigation_strategy_plot(df_mitigation,
  "mitigation_constructed_p_values",
  p_values = df_mitigation_p_values,
  exclusive_column_for_lpr2 = "Unmitigated"
)

p
```

```{r}
ggsave(here::here("figures", "individual_unique_diagnoses_analyses", "constructed_individual_unique_diagnoses_mitigation_with_p_values.png"), 
       plot = p, 
       width = 10,
       height = 5,
       dpi = 600)
```