library("pacman")

p_load(testthat, here)

source(here("src", "functions.r"))

test_dfs <- list()

###

df_general <- data.frame(
  stringsAsFactors = FALSE,
  adiagnosekode = c("F203", "F203", "G8410", "F99"),
  prioritet = c("Planlagt", "Planlagt", "Planlagt", "Planlagt")
)

df_psych_only <- keep_only_psych_visits(df_general)

test_that("Basic utility functions", {
  expect_equal(df_psych_only$adiagnosekode, c("F203", "F203"))
  expect_equal(df_psych_only$prioritet, c("Planlagt", "Planlagt"))
})

###

df_convert_seq_to_visits_in <- data.frame(
    stringsAsFactors = FALSE,
    constructed_id = c("1660002P1","1660002P1","1660002P2","1660002P2","1660002P3"),
              date = c("2016-01-14","2016-02-01","2016-02-29","2016-10-10","2017-01-27")
)

df_convert_seq_to_visits_out <- convert_visits_to_sequences(df_convert_seq_to_visits_in,
                                                            sequence_id_col = constructed_id,
                                                            date_col = date)

test_that("convert_visits_to_sequences", {
  expect_equal(df_convert_seq_to_visits_out$constructed_id, c("1660002P1", "1660002P2", "1660002P3"))
  expect_equal(df_convert_seq_to_visits_out$sequence_start_date, c("2016-01-14", "2016-02-29", "2017-01-27"))
  expect_equal(df_convert_seq_to_visits_out$sequence_end_date, c("2016-02-01", "2016-10-10", "2017-01-27"))
})


df_test <- convert_visits_to_sequences(df_convert_seq_to_visits_in,
                                       sequence_id_col = constructed_id,
                                       date_col = date)

### Count open records in sequence

df_count_in <- tibble::tribble(
  ~constructed_id,        ~date, ~sequence_start_date, ~sequence_end_date,
  "1660002P1", "2016-01-14",         "2016-01-14",       "2016-02-01",
  "1660002P2", "2016-02-29",         "2016-02-27",       "2016-10-10",
  "1660002P3", "2016-02-29",         "2016-02-27",       "2016-10-10",
  "1660002P4", "2016-01-14",         "2016-02-27",       "2017-03-27",
  "1660002P5", "2017-01-12",         "2017-01-12",       "2017-03-27"
) %>% mutate(sequence_start_date = ymd(sequence_start_date),
             sequence_end_date = ymd(sequence_end_date))



df_c_o <- count_open_sequences_in_period(df_count_in)

test_that("convert_visits_to_sequences", {
  expect_equal(df_c_o$date, ymd(c("2016-01-14","2016-04-14","2016-07-14", "2016-10-14","2017-01-14")))
  expect_equal(df_c_o$count, c(1, 3, 3, 1, 2))
})


### Collapse sequences if overlapping

source(here("src", "functions.r"))

df_test_collapse_sequences <- tibble::tribble(
  ~dw_ek_borger, ~sequence_start_date, ~sequence_end_date,
  "1660002P1", "2016-01-14",         "2017-03-01",
  "1660002P1", "2016-01-26",         "2016-02-27",
  "1660002P1", "2016-02-10",         "2016-04-01",
  "1660002P1", "2018-02-10",         "2018-04-01",
  "1660002P4", "2016-01-14",         "2016-02-27",
  "1660002P5", "2017-01-12",         "2017-01-12") %>%
  mutate(sequence_start_date = ymd(sequence_start_date),
         sequence_end_date = ymd(sequence_end_date)) %>% 
  collapse_sequences_if_same_patient()

head(df_test_collapse_sequences)


test_that("Collapse sequences if overlapping", {
  expect_equal(df_test_collapse_sequences$dw_ek_borger, c("1660002P1", "1660002P1", "1660002P4", "1660002P5"))
  expect_equal(df_test_collapse_sequences$sequence_start_date, ymd(c("2016-01-14","2018-02-10","2016-01-14","2017-01-12")))
})


### Test recoding functions
test_dfs$recode_most_severe <- tibble::tribble(
  ~dw_sk_lpr3forloebsansvar, ~dw_sk_kontakt, ~adiagnosekode,
  1,             -1,         "F0",
  1,             -1,         "F1",
  1,             -1,         "F9",
  2,             -1,         "F9",
  2,             -1,         "F4",
  3,             -1,         "F5",
  -1,             1,         "F9",
  -1,             1,         "F5",
  -1,             1,         "F9",
  -1,             1,         "F4"
) %>% recode_with_most_severe_diagnosis_for_sequence(
  id_col = dw_sk_lpr3forloebsansvar
) %>% 
  arrange(dw_sk_lpr3forloebsansvar, dw_sk_kontakt)


test_that("Recode with most severe", {
  ## Testing 'test_dfs$recode_most_severe'                                    ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing class
  expect_equal(
    class(test_dfs$recode_most_severe),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    test_dfs$recode_most_severe[["dw_sk_lpr3forloebsansvar"]],
    c(-1, -1, -1, -1, 1, 1, 1, 2, 2, 3),
    tolerance = 1e-4)
  expect_equal(
    test_dfs$recode_most_severe[["dw_sk_kontakt"]],
    c(1, 1, 1, 1, -1, -1, -1, -1, -1, -1),
    tolerance = 1e-4)
  expect_equal(
    test_dfs$recode_most_severe[["adiagnosekode"]],
    c("F9", "F5", "F9", "F4", "F0", "F0", "F0", "F4", "F4", "F5"),
    fixed = TRUE)
  # Testing column names
  expect_equal(
    names(test_dfs$recode_most_severe),
    c("dw_sk_lpr3forloebsansvar", "dw_sk_kontakt", "adiagnosekode"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(test_dfs$recode_most_severe),
    c("numeric", "numeric", "character"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(test_dfs$recode_most_severe),
    c("double", "double", "character"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(test_dfs$recode_most_severe),
    c(10L, 3L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(test_dfs$recode_most_severe)),
    character(0),
    fixed = TRUE)
  ## Finished testing 'test_dfs$recode_most_severe'                           ####
})