---
editor_options:
  chunk_output_type: inline
output:
  html_document: default
always_allow_html: yes
---
# Stability connected series, seq_id
## Data wrangling 
```{r}
df_raw <- get_fct("FOR_besoeg_fysiske_fremmoeder_inkl_2021") %>%
  clean_sql_import() %>% 
  filter(ymd(start_date_str) < as.Date(datotid_start), 
         ymd(end_date_str) > as.Date(datotid_start))

df_psych_only <- df_raw %>%
  keep_only_psych_visits() %>%
  select(
    "dw_ek_borger",
    "datotid_start",
    "dw_sk_lpr3forloebsansvar",
    "adiagnosekode"
  ) %>%
  mutate(adiagnosekode = substring(adiagnosekode, 1, 2))

log_time()
```

```{r}
df_numbered_visits <- df_psych_only %>%
  group_by(dw_sk_lpr3forloebsansvar) %>%
  arrange(datotid_start, .by_group = T) %>%
  mutate(contact_nr = row_number()) %>%
  group_by(dw_sk_lpr3forloebsansvar) %>%
  mutate(total_contacts = max(contact_nr))

log_time()
```

# Plot Alluvial diagram
```{r}
## Changes over n_visits
df_treatment_courses <- df_numbered_visits %>%
  ## filter(total_contacts > 1) %>% ## Want to also visualise contacts that aren't part of a connected series
  group_by(dw_sk_lpr3forloebsansvar) %>%
  mutate(first_diagnosis = str_c(adiagnosekode)) %>%
  mutate(last_diagnosis = str_c(last(adiagnosekode))) %>%
  filter(contact_nr == 1)

log_time()
```


```{r}
df_treatment_courses_filtered <- df_treatment_courses %>%
  filter(substr(first_diagnosis, 1, 1) == "Z" | substr(first_diagnosis, 1, 1) == "F") %>%
  mutate(first_diagnosis = ifelse(substr(first_diagnosis, 1, 1) == "Z", "ZX", first_diagnosis)) %>%
  mutate(last_diagnosis = ifelse(substr(last_diagnosis, 1, 1) == "Z", "ZX", last_diagnosis)) %>%
  mutate(diagnosis_changed = ifelse(first_diagnosis == last_diagnosis, 0, 1)) %>%
  filter(substr(last_diagnosis, 1, 1) == "Z" | substr(last_diagnosis, 1, 1) == "F") %>%
  filter(first_diagnosis != "ZX") %>%
  filter(last_diagnosis != "ZX")

log_time()
```

```{r}
df_treatment_course_counts <- df_treatment_courses_filtered %>%
  group_by(first_diagnosis, last_diagnosis) %>%
  summarize(n = n()) %>%
  filter(n > 5)

log_time()
```

```{r fig.height=20, fig.width=20}
source(here("src", "stability_connected_series_functions.r"))

alluvial <- save_alluvial_plot(df = df_treatment_course_counts, 
                   filename = "allu_first_last_seq_id")

alluvial
```

```{r}
first_diagnosis_table <- gen_first_diagnosis_table(df_treatment_courses_filtered)
write.csv(first_diagnosis_table, here("tables", "first_diagnosis.csv"))

last_diagnosis_table <- gen_last_diagnosis_table(df_treatment_courses_filtered)
write.csv(last_diagnosis_table, here("tables", "last_diagnosis.csv"))
```

```{r}
library("kableExtra")

first_diagnosis_table %>%
  kbl() %>%
  kable_classic_2(full_width = F)
```
```{r}
library("kableExtra")

last_diagnosis_table %>%
  kbl() %>%
  kable_classic_2(full_width = F)
```
