---
editor_options:
  chunk_output_type: inline
output:
  html_document: default
always_allow_html: yes
---
# Stability connected series, same_clinic
## General data wrangling
```{r get-raw}
df_raw_outpatient <- get_fct("FOR_besoeg_fysiske_fremmoeder_inkl_2021") %>%
  clean_sql_import()

df_outpatient_visits_preprocessed <- df_raw_outpatient %>%
  mutate(no_threshold_patient_clinic_id = paste0(dw_ek_borger, shakafskode_besoeg)) %>%
  keep_only_psych_visits() %>%
  select(
    dw_ek_borger,
    datotid_start,
    adiagnosekode,
    ambbesoeg,
    dw_sk_lpr3forloebsansvar,
    dw_sk_kontakt,
    shakafskode_besoeg,
    no_threshold_patient_clinic_id
  ) %>%
  add_LPR23_quarter_column() %>%
  filter(period > ymd("2012-05-01")) %>%
  filter(period < ymd("2021-06-01"))
```

## No threshold
### Data wrangling
```{r construct-no-threshold}
df_visits_with_clinic_id <- df_outpatient_visits_preprocessed %>%
  keep_only_psych_visits() %>%
  mutate(adiagnosekode = substring(adiagnosekode, 1, 2)) %>%
  add_patient_and_clinic_uid(
    clinic_id_col = shakafskode_besoeg,
    patient_id_col = dw_ek_borger
  )
```

```{r}
df_visits_with_clinic_id_numbered <- df_visits_with_clinic_id %>%
  group_by(patient_clinic_id) %>%
  arrange(datotid_start, .by_group = T) %>%
  mutate(contact_nr = row_number()) %>%
  group_by(patient_clinic_id) %>%
  mutate(total_contacts = max(contact_nr))

log_time()
```

### Plotting
```{r}
## Changes over n_visits
df_treatment_courses <- df_visits_with_clinic_id_numbered %>%
  ## filter(total_contacts > 1) %>% ## Want to also visualise contacts that aren't part of a connected series
  group_by(patient_clinic_id) %>%
  mutate(first_diagnosis = str_c(adiagnosekode)) %>%
  mutate(last_diagnosis = str_c(last(adiagnosekode))) %>%
  filter(contact_nr == 1)

log_time()
```


```{r}
df_treatment_courses_filtered <- df_treatment_courses %>%
  filter(substr(first_diagnosis, 1, 1) == "Z" | substr(first_diagnosis, 1, 1) == "F") %>%
  mutate(first_diagnosis = ifelse(substr(first_diagnosis, 1, 1) == "Z", "ZX", first_diagnosis)) %>%
  mutate(last_diagnosis = ifelse(substr(last_diagnosis, 1, 1) == "Z", "ZX", last_diagnosis)) %>%
  mutate(diagnosis_changed = ifelse(first_diagnosis == last_diagnosis, 0, 1)) %>%
  filter(substr(last_diagnosis, 1, 1) == "Z" | substr(last_diagnosis, 1, 1) == "F") %>%
  filter(first_diagnosis != "ZX") %>%
  filter(last_diagnosis != "ZX")

log_time()
```

```{r}
df_treatment_courses_filtered_counted <- df_treatment_courses_filtered %>%
  group_by(first_diagnosis, last_diagnosis) %>%
  summarize(n = n()) %>%
  filter(n > 5)

log_time()
```

```{r}
source(here("src", "stability_connected_series_functions.r"))

save_alluvial_plot(
  df = df_treatment_courses_filtered_counted,
  filename = "allu_first_last_same_clinic_no_threshold"
)

log_time()
```

```{r}
first_diagnosis_table <- gen_first_diagnosis_table(df_treatment_courses_filtered)

last_diagnosis_table <- gen_last_diagnosis_table(df_treatment_courses_filtered)
```

### Tables
```{r}
library("kableExtra")

first_diagnosis_table %>%
  kbl() %>%
  kable_classic_2(full_width = F)
```
```{r}
library("kableExtra")

last_diagnosis_table %>%
  kbl() %>%
  kable_classic_2(full_width = F)
```