---
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r}
library(here)
```


## Inpatient flow
### Inpatient: Select variables and join LPR2/LPR3 
```{r}
df_inpatient_lpr3 <- df_raw_lpr3 %>%
  filter(pt_type == "Indlagt") %>%
  select(dw_ek_borger, adiagnosekode, datotid_lpr3kontaktstart) %>%
  rename(datotid_start = datotid_lpr3kontaktstart)

df_inpatient_lpr2 <- df_raw_lpr2_inpatient %>%
  select(dw_ek_borger, adiagnosekode, datotid_indlaeggelse) %>%
  rename(datotid_start = datotid_indlaeggelse)

df_all_inpatient_visits <- bind_rows(df_inpatient_lpr2, df_inpatient_lpr3) %>%
  filter(as.Date(datotid_start) < ymd("2021-06-01"))

log_time()
```

```{r}
df_inpatient_by_subcp <- df_all_inpatient_visits %>%
  keep_only_psych_visits() %>%
  truncate_diagnosis_to_letter_and_digit() %>%
  add_LPR23_quarter_column()

## Examine date parsing
## df_examine <- df_inpatient_by_subcp %>%
##   filter(datotid_start > ymd("2018-09-01")) %>%
##   filter(datotid_start < ymd("2019-04-01"))

df_n_patients_by_quarter <- df_inpatient_by_subcp %>%
  add_column_unique_pt_in_period()

df_n_patients_by_diag_by_quarter <- df_inpatient_by_subcp %>%
  add_column_n_with_diagnosis_in_period()

df_prop_of_patients_with_diag <- prop_of_patients_with_diagnosis_by_subcp(
  df_n_patients_by_quarter,
  df_n_patients_by_diag_by_quarter
)

write_csv(df_prop_of_patients_with_diag, here("csv", "df_prop_of_patients_with_diag"))

log_time()
```

```{r}
source(here("src", "subchapter_props_functions.r"))

df_prop_of_patients_with_diag <- read_csv(here("csv", "df_prop_of_patients_with_diag"))

graph_subchapter_props(df_prop_of_patients_with_diag,
  filename = "examine_inpatient_same_y_axes",
  date_range = c(ymd("2013-01-01"), ymd("2021-01-01")),
  with_mitigation = FALSE,
  ylabel = "Proportion of inpatients with within-quarter incident main diagnosis from chapter",
  tag = "A"
)

graph_subchapter_props(df_prop_of_patients_with_diag,
  filename = "examine_inpatient_free_y_axes",
  date_range = c(ymd("2013-01-01"), ymd("2021-01-01")),
  with_mitigation = FALSE,
  ylabel = "Proportion of inpatients with within-quarter incident main diagnosis from chapter",
  tag = "B"
)

log_time()
```

```{r}
df_prop_of_patients_with_diag %>%
  mutate(
    lpr3 = if_else(period < "2019-02-03", 0, 1),
    period = yearquarter(period)
  ) %>%
  select(prop, adiagnosekode, period, lpr3) %>%
  as_tsibble(key = adiagnosekode, index = period) %>%
  model(arima = ARIMA(prop ~ 1 + lpr3 + pdq(0, 0, 0) + PDQ(0, 0, 0))) %>%
  coef() %>%
  select(!.model)
```