---
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r}
library(here)
```

# Subchapter props, outpatient in same clinic
```{r}
source(here::here("src", "functions.r"))

df_outpatient_visits_clinic_id <- df_outpatient_for_subchapter %>%
  keep_only_psych_visits() %>%
  add_patient_and_clinic_uid(
    clinic_id_col = clinic,
    patient_id_col = dw_ek_borger
  ) %>%
  filter(period < ymd("2021-06-01"))
```

#### Default 
```{r}
df_n_with_diag_in_period <- df_outpatient_visits_clinic_id %>%
  add_column_n_with_diagnosis_in_period()

df_prop_of_patients_with_diag_from_subcp <- prop_of_patients_with_diagnosis_by_subcp(
  df_n_outpatients_by_quarter,
  df_n_with_diag_in_period
)
```


#### Final visit
```{r}
df_visits_relabel_final_diag <- df_outpatient_visits_clinic_id %>%
  recode_diagnoses_with_last_in_sequence(constructed_id)

df_n_patients_by_subcp_by_quarter_relabel_final_diag <- df_visits_relabel_final_diag %>%
  add_column_n_with_diagnosis_in_period()

df_prop_diag_constructed_sequence_final_visit_only <- prop_of_patients_with_diagnosis_by_subcp(
  df_n_outpatients_by_quarter,
  df_n_patients_by_subcp_by_quarter_relabel_final_diag
)
```
#### Most severe visit
```{r}
df_visits_relabel_most_severe_diag <- df_outpatient_visits_clinic_id %>%
  relabel_diag_most_severe(constructed_id)

df_n_patients_by_subcp_by_quarter_relabel_most_severe <- df_visits_relabel_most_severe_diag %>%
  add_column_n_with_diagnosis_in_period()

df_prop_diag_constructed_sequence_most_severe_diag <- prop_of_patients_with_diagnosis_by_subcp(
  df_n_outpatients_by_quarter,
  df_n_patients_by_subcp_by_quarter_relabel_most_severe
)
```

### Plot
```{r}

### Join with the receiver dataframe
df_n_patients_by_subcp_by_quarter_combined <- mutate(df_prop_of_patients_with_diag_from_subcp, origin = "Unchanged") %>%
  bind_rows(mutate(df_prop_diag_constructed_sequence_most_severe_diag, origin = "Most severe")) %>%
  bind_rows(mutate(df_prop_diag_constructed_sequence_final_visit_only, origin = "Final visit"))

write_csv(df_n_patients_by_subcp_by_quarter_combined, here("csv", "df_n_patients_by_subcp_by_quarter_combined.csv"))

log_time()
```

```{r}
### Plot
df_n_patients_by_subcp_by_quarter_combined <- read_csv(here("csv", "df_n_patients_by_subcp_by_quarter_combined.csv"))

source(here::here("src", "subchapter_props_functions.r"))

graph_subchapter_props(df_n_patients_by_subcp_by_quarter_combined,
  filename = "examine_mitigation_constructed_full_same_y_axes",
  date_range = c(ymd("2011-06-01"), ymd("2021-01-01")),
  ylabel = "Proportion of outpatients with within-quarter incident main diagnosis from chapter",
  tag = "A"
)

graph_subchapter_props(df_n_patients_by_subcp_by_quarter_combined,
  filename = "examine_mitigation_constructed_full_free_y_axes",
  date_range = c(ymd("2011-06-01"), ymd("2021-01-01")),
  ylabel = "Proportion of outpatients with within-quarter incident main diagnosis from chapter",
  tag = "B"
)

log_time()
```

### Plot with p-values
```{r}
df_n_patients_by_subcp_by_quarter_combined_without_first_quarters <- df_n_patients_by_subcp_by_quarter_combined %>%
  filter(period > "2013-01-01")
```

```{r}
pacman::p_load(fable, tsibble, feasts, urca)


df_n_patients_by_subcp_by_quarter_combined_without_first_quarters_p_values <- df_n_patients_by_subcp_by_quarter_combined_without_first_quarters %>%
  mutate(
    lpr3 = if_else(period < "2019-02-03", 0, 1),
    period = yearquarter(period)
  ) %>%
  select(prop, adiagnosekode, period, origin, lpr3) %>%
  as_tsibble(key = c(origin, adiagnosekode), index = period) %>%
  model(arima = ARIMA(prop ~ 1 + lpr3 + pdq(0, 0, 0) + PDQ(0, 0, 0))) %>%
  coef() %>%
  select(!.model) %>%
  filter(term == "lpr3")

## add the needed x (period) and y (prop) values for plotting
df_n_patients_by_subcp_by_quarter_combined_without_first_quarters_p_values <- df_n_patients_by_subcp_by_quarter_combined_without_first_quarters %>%
  filter(period == max(period)) %>%
  select(period, prop, origin, adiagnosekode) %>%
  left_join(df_n_patients_by_subcp_by_quarter_combined_without_first_quarters_p_values, by = c("origin", "adiagnosekode")) %>%
  mutate(corrected_p <- p.adjust(p.value, "fdr", n = 70), # 30 comparisons
    significant = if_else(corrected_p < 0.05, "*", "")
  ) %>%
  mutate(adiagnosekode = case_when(
    adiagnosekode == "F0" ~ "F0 - Organic disorders",
    adiagnosekode == "F1" ~ "F1 - Substance abuse",
    adiagnosekode == "F2" ~ "F2 - Psychotic disorders",
    adiagnosekode == "F3" ~ "F3 - Mood disorders",
    adiagnosekode == "F4" ~ "F4 - Neurotic & stress-related",
    adiagnosekode == "F5" ~ "F5 - Eating & sleeping disorders",
    adiagnosekode == "F6" ~ "F6 - Personality disorders",
    adiagnosekode == "F7" ~ "F7 - Mental retardation",
    adiagnosekode == "F8" ~ "F8 - Developmental disorders",
    adiagnosekode == "F9" ~ "F9 - Child & adolescent disorders"
  ))
```



```{r}
source(here("src", "subchapter_props_functions.r"))


graph_subchapter_props(df_n_patients_by_subcp_by_quarter_combined_without_first_quarters,
  filename = "examine_mitigation_constructed_without_first_quarters_full_same_y_axes_with_p_values",
  date_range = c(ymd("2013-01-01"), ymd("2022-05-01")),
  ylabel = "Proportion of outpatients with within-quarter incident main diagnosis from chapter",
  p_values = df_n_patients_by_subcp_by_quarter_combined_without_first_quarters_p_values,
  nudge_constant = 0.02,
  tag = "A"
)

graph_subchapter_props(df_n_patients_by_subcp_by_quarter_combined_without_first_quarters,
  filename = "examine_mitigation_constructed_without_first_quarters_full_free_y_axes_with_p_values",
  date_range = c(ymd("2013-01-01"), ymd("2022-10-01")),
  ylabel = "Proportion of outpatients with within-quarter incident main diagnosis from chapter",
  p_values = df_n_patients_by_subcp_by_quarter_combined_without_first_quarters_p_values,
  nudge_frac = 0.02,
  tag = "B"
)
```