---
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r}
source(here("rmd", "subchapter_props", "0_setup_env.r"))
```
# Subchapter props, outpatient constructed
## Run 1a_outpatient_naive.rmd first!
### Construct sequences
```{r}
source(here::here("src", "functions.r"))

df_constructed_outpatient_series <- df_outpatient_for_subchapter %>%
  keep_only_psych_visits() %>%
  construct_sequences(
    clinic_id_col = clinic,
    patient_id_col = dw_ek_borger,
    date_col = datotid_start,
    threshold_months = 0,
    verbose = TRUE
  ) %>% 
  filter(period < ymd("2021-06-01"))
```

#### Default 
```{r}
df_n_with_diag_in_period_constructed_default <- df_constructed_outpatient_series %>%
  add_column_n_with_diagnosis_in_period()

df_prop_diag_constructed_sequence_default <- calc_prop_of_unique_patients_with_diagnosis(
  df_unique_in_period_outpatient,
  df_n_with_diag_in_period_constructed_default
)
```


#### Final visit
```{r}
df_constructed_sequence_final_visit_only <- df_constructed_outpatient_series %>%
  recode_diagnoses_with_last_in_sequence(constructed_id)

df_n_with_diag_in_period_constructed_final_diag <- df_constructed_sequence_final_visit_only %>%
  add_column_n_with_diagnosis_in_period()

df_prop_diag_constructed_sequence_final_visit_only <- calc_prop_of_unique_patients_with_diagnosis(
  df_unique_in_period_outpatient,
  df_n_with_diag_in_period_constructed_final_diag
)
```
#### Most severe visit
```{r}
df_constructed_sequence_most_severe_diag <- df_constructed_outpatient_series %>%
  recode_with_most_severe_diagnosis_for_sequence(constructed_id)

df_n_with_diag_in_period_constructed_most_severe_diag <- df_constructed_sequence_most_severe_diag %>%
  add_column_n_with_diagnosis_in_period()

df_prop_diag_constructed_sequence_most_severe_diag <- calc_prop_of_unique_patients_with_diagnosis(
  df_unique_in_period_outpatient,
  df_n_with_diag_in_period_constructed_most_severe_diag
)
```

### Plot
```{r}

### Join with the receiver dataframe
df_examine_mitigation_constructed_sequences <- mutate(df_prop_diag_constructed_sequence_default, origin = "Unchanged") %>%
  bind_rows(mutate(df_prop_diag_constructed_sequence_most_severe_diag, origin = "Most severe")) %>%
  bind_rows(mutate(df_prop_diag_constructed_sequence_final_visit_only, origin = "Final visit"))

write_csv(df_examine_mitigation_constructed_sequences, here("csv", "df_examine_mitigation_constructed_sequences.csv"))

log_time()
```

```{r}
### Plot
df_examine_mitigation_constructed_sequences <- read_csv(here("csv", "df_examine_mitigation_constructed_sequences.csv"))

source(here::here("src", "subchapter_props_functions.r"))

graph_subchapter_props(df_examine_mitigation_constructed_sequences,
  filename = "examine_mitigation_constructed_full_same_y_axes",
  date_range = c(ymd("2011-06-01"), ymd("2021-01-01")),
  ylabel = "Proportion of outpatients with incident main diagnosis from chapter",
  tag = "A"
)

graph_subchapter_props(df_examine_mitigation_constructed_sequences,
  filename = "examine_mitigation_constructed_full_free_y_axes",
  date_range = c(ymd("2011-06-01"), ymd("2021-01-01")),
  ylabel = "Proportion of outpatients with incident main diagnosis from chapter",
  tag = "B"
)

log_time()
```

### Plot with p-values
```{r}
df_examine_mitigation_constructed_sequences_without_first_quarters <- df_examine_mitigation_constructed_sequences %>%
  filter(period > "2013-01-01")
```

```{r}
pacman::p_load(fable, tsibble, feasts, urca)


df_examine_mitigation_constructed_sequences_without_first_quarters_p_values <- df_examine_mitigation_constructed_sequences_without_first_quarters %>%
  mutate(
    lpr3 = if_else(period < "2019-02-03", 0, 1),
    period = yearquarter(period)
  ) %>%
  select(prop, adiagnosekode, period, origin, lpr3) %>%
  as_tsibble(key = c(origin, adiagnosekode), index = period) %>%
  model(arima = ARIMA(prop ~ 1 + lpr3 + pdq(0, 0, 0) + PDQ(0, 0, 0))) %>%
  coef() %>%
  select(!.model) %>%
  filter(term == "lpr3")

## add the needed x (period) and y (prop) values for plotting
df_examine_mitigation_constructed_sequences_without_first_quarters_p_values <- df_examine_mitigation_constructed_sequences_without_first_quarters %>%
  filter(period == max(period)) %>%
  select(period, prop, origin, adiagnosekode) %>%
  left_join(df_examine_mitigation_constructed_sequences_without_first_quarters_p_values, by = c("origin", "adiagnosekode")) %>%
  mutate(corrected_p <- p.adjust(p.value, "fdr", n = 70), # 30 comparisons
    significant = if_else(corrected_p < 0.05, "*", "")
  )

df_examine_mitigation_constructed_sequences_without_first_quarters_p_values
```



```{r}
source(here("src", "subchapter_props_functions.r"))


graph_subchapter_props(df_examine_mitigation_constructed_sequences_without_first_quarters,
  filename = "examine_mitigation_constructed_without_first_quarters_full_same_y_axes_with_p_values",
  date_range = c(ymd("2013-01-01"), ymd("2022-05-01")),
  ylabel = "Proportion of outpatients with incident main diagnosis from chapter",
  p_values = df_examine_mitigation_constructed_sequences_without_first_quarters_p_values,
  nudge_constant = 0.02,
  tag = "A"
)

graph_subchapter_props(df_examine_mitigation_constructed_sequences_without_first_quarters,
  filename = "examine_mitigation_constructed_without_first_quarters_full_free_y_axes_with_p_values",
  date_range = c(ymd("2013-01-01"), ymd("2022-10-01")),
  ylabel = "Proportion of outpatients with incident main diagnosis from chapter",
  p_values = df_examine_mitigation_constructed_sequences_without_first_quarters_p_values,
  nudge_frac = 0.02,
  tag = "B"
)
```