---
title: "individual_unique_diagnoses_by_date"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r}
source("0_setup_env_unique_diagnoses.r")
```

# Data wrangling 
## Base pre-processing
```{r}
source(here("src", "functions.r"))

df_outpatient_preprocessed <- df_raw_outpatient %>%
  mutate(no_threshold_constructed_id = paste0(dw_ek_borger, shakgeografiafskode_besoeg)) %>%
  keep_only_psych_visits() %>%
  select(
    dw_ek_borger,
    datotid_start,
    adiagnosekode,
    ambbesoeg,
    dw_sk_lpr3forloebsansvar,
    dw_sk_kontakt,
    shakgeografiafskode_besoeg,
    no_threshold_constructed_id
  ) %>%
  add_LPR23_quarter_column() %>%
  filter(period > ymd("2012-05-01"))
```

# No threshold
## Construct sequences
```{r}
source(here("src", "functions.r"))

df_outpatient_constructed_no_threshold <- df_outpatient_preprocessed %>%
  construct_sequences(
    clinic_id_col = shakgeografiafskode_besoeg,
    patient_id_col = dw_ek_borger,
    date_col = datotid_start,
    threshold_months = 0,
    verbose = TRUE
  )
```

```{r}
source(here("src", "functions.r"))

df_outpatient_constructed_no_threshold_default <- df_outpatient_constructed_no_threshold %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

df_outpatient_constructed_no_threshold_most_severe <- df_outpatient_constructed_no_threshold %>%
  recode_with_most_severe_diagnosis_for_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

df_outpatient_constructed_no_threshold_last_visit_only <- df_outpatient_constructed_no_threshold %>%
  recode_diagnoses_with_last_in_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

log_time()
```

## Plotting
```{r fig.height=5, fig.width=10}
log_time()
source(here("src", "individual_unique_diagnoses_functions.r"))

df_mitigation_constructed_no_threshold_plot <- df_outpatient_constructed_no_threshold_default %>%
  filter(period > ymd("2012-12-31")) %>%
  mutate(origin = "outpatient_all") %>%
  bind_rows(mutate(df_outpatient_constructed_no_threshold_most_severe, origin = "most_severe")) %>%
  bind_rows(mutate(df_outpatient_constructed_no_threshold_last_visit_only, origin = "final_visit")) %>%
  mutate(period = as.Date(period)) %>%
  filter(period > ymd("2019-01-01") | origin == "outpatient_all") %>%
  mutate(origin = case_when(
    origin == "outpatient_all" ~ "Unmitigated",
    origin == "final_visit" ~ "Final visit",
    origin == "most_severe" ~ "Most severe"
  ))

mitigation_constructed_no_threshold_plot <- save_mitigation_strategy_plot(df_mitigation_constructed_no_threshold_plot, "mitigation_constructed_no_threshold")

mitigation_constructed_no_threshold_plot
```

# 1m threshold
```{r}
source(here("src", "functions.r"))

df_outpatient_constructed_1m_threshold <- df_outpatient_preprocessed %>%
  construct_sequences(
    clinic_id_col = shakgeografiafskode_besoeg,
    patient_id_col = dw_ek_borger,
    date_col = datotid_start,
    threshold_months = 1,
    verbose = TRUE
  )
```

## Construct ssequences
```{r}
df_outpatient_constructed_1m_threshold_default <- df_outpatient_constructed_1m_threshold %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

df_outpatient_constructed_1m_threshold_most_severe <- df_outpatient_constructed_1m_threshold %>%
  recode_with_most_severe_diagnosis_for_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

df_outpatient_constructed_1m_threshold_last_visit_only <- df_outpatient_constructed_1m_threshold %>%
  recode_diagnoses_with_last_in_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)


log_time()
```

## Plotting
```{r fig.height=5, fig.width=10}
log_time()
source(here("src", "individual_unique_diagnoses_functions.r"))

df_mitigation_constructed_1m_threshold_plot <- df_outpatient_constructed_1m_threshold_default %>%
  filter(period > ymd("2012-12-31")) %>%
  mutate(origin = "outpatient_all") %>%
  bind_rows(mutate(df_outpatient_constructed_1m_threshold_most_severe, origin = "most_severe")) %>%
  bind_rows(mutate(df_outpatient_constructed_1m_threshold_last_visit_only, origin = "final_visit")) %>%
  mutate(period = as.Date(period)) %>%
  filter(period > ymd("2019-01-01") | origin == "outpatient_all") %>%
  mutate(origin = case_when(
    origin == "outpatient_all" ~ "Unmitigated",
    origin == "final_visit" ~ "Final visit",
    origin == "most_severe" ~ "Most severe"
  ))

mitigation_constructed_1m_threshold_plot <- save_mitigation_strategy_plot(df_mitigation_constructed_1m_threshold_plot, "mitigation_constructed_1m_threshold")

mitigation_constructed_1m_threshold_plot
```


# 2m threshold
```{r}
source(here("src", "functions.r"))

df_outpatient_constructed_2m_threshold <- df_outpatient_preprocessed %>%
  construct_sequences(
    clinic_id_col = shakgeografiafskode_besoeg,
    patient_id_col = dw_ek_borger,
    date_col = datotid_start,
    threshold_months = 2,
    verbose = TRUE
  )
```

## Construct ssequences
```{r}
df_outpatient_constructed_2m_threshold_default <- df_outpatient_constructed_2m_threshold %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

df_outpatient_constructed_2m_threshold_most_severe <- df_outpatient_constructed_2m_threshold %>%
  recode_with_most_severe_diagnosis_for_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

df_outpatient_constructed_2m_threshold_last_visit_only <- df_outpatient_constructed_2m_threshold %>%
  recode_diagnoses_with_last_in_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)


log_time()
```

## Plotting
```{r fig.height=5, fig.width=10}
log_time()
source(here("src", "individual_unique_diagnoses_functions.r"))

df_mitigation_constructed_2m_threshold_plot <- df_outpatient_constructed_2m_threshold_default %>%
  filter(period > ymd("2012-12-31")) %>%
  mutate(origin = "outpatient_all") %>%
  bind_rows(mutate(df_outpatient_constructed_2m_threshold_most_severe, origin = "most_severe")) %>%
  bind_rows(mutate(df_outpatient_constructed_2m_threshold_last_visit_only, origin = "final_visit")) %>%
  mutate(period = as.Date(period)) %>%
  filter(period > ymd("2019-01-01") | origin == "outpatient_all") %>%
  mutate(origin = case_when(
    origin == "outpatient_all" ~ "Unmitigated",
    origin == "final_visit" ~ "Final visit",
    origin == "most_severe" ~ "Most severe"
  ))

mitigation_constructed_2m_threshold_plot <- save_mitigation_strategy_plot(df_mitigation_constructed_2m_threshold_plot, "mitigation_constructed_2m_threshold")

mitigation_constructed_2m_threshold_plot
```


# 3m threshold
```{r}
source(here("src", "functions.r"))

df_outpatient_constructed_3m_threshold <- df_outpatient_preprocessed %>%
  construct_sequences(
    clinic_id_col = shakgeografiafskode_besoeg,
    patient_id_col = dw_ek_borger,
    date_col = datotid_start,
    threshold_months = 3,
    verbose = TRUE
  )
```

## Construct ssequences
```{r}
df_outpatient_constructed_3m_threshold_default <- df_outpatient_constructed_3m_threshold %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

df_outpatient_constructed_3m_threshold_most_severe <- df_outpatient_constructed_3m_threshold %>%
  recode_with_most_severe_diagnosis_for_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

df_outpatient_constructed_3m_threshold_last_visit_only <- df_outpatient_constructed_3m_threshold %>%
  recode_diagnoses_with_last_in_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)


log_time()
```

## Plotting
```{r fig.height=5, fig.width=10}
log_time()
source(here("src", "individual_unique_diagnoses_functions.r"))

df_mitigation_constructed_3m_threshold_plot <- df_outpatient_constructed_3m_threshold_default %>%
  filter(period > ymd("2012-12-31")) %>%
  mutate(origin = "outpatient_all") %>%
  bind_rows(mutate(df_outpatient_constructed_3m_threshold_most_severe, origin = "most_severe")) %>%
  bind_rows(mutate(df_outpatient_constructed_3m_threshold_last_visit_only, origin = "final_visit")) %>%
  mutate(period = as.Date(period)) %>%
  filter(period > ymd("2019-01-01") | origin == "outpatient_all") %>%
  mutate(origin = case_when(
    origin == "outpatient_all" ~ "Unmitigated",
    origin == "final_visit" ~ "Final visit",
    origin == "most_severe" ~ "Most severe"
  ))

mitigation_constructed_3m_threshold_plot <- save_mitigation_strategy_plot(df_mitigation_constructed_3m_threshold_plot, "mitigation_constructed_3m_threshold")

mitigation_constructed_3m_threshold_plot
```

# 6m threshold
```{r}
source(here("src", "functions.r"))

df_outpatient_constructed_6m_threshold <- df_outpatient_preprocessed %>%
  construct_sequences(
    clinic_id_col = shakgeografiafskode_besoeg,
    patient_id_col = dw_ek_borger,
    date_col = datotid_start,
    threshold_months = 6,
    verbose = TRUE
  )
```

## Construct ssequences
```{r}
df_outpatient_constructed_6m_threshold_default <- df_outpatient_constructed_6m_threshold %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

df_outpatient_constructed_6m_threshold_most_severe <- df_outpatient_constructed_6m_threshold %>%
  recode_with_most_severe_diagnosis_for_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)

df_outpatient_constructed_6m_threshold_last_visit_only <- df_outpatient_constructed_6m_threshold %>%
  recode_diagnoses_with_last_in_sequence(constructed_id) %>%
  gen_unique_diagnoses_pr_patient(confidence_intervals = TRUE, truncation_levels = FALSE)


log_time()
```

## Plotting
```{r fig.height=5, fig.width=10}
log_time()
source(here("src", "individual_unique_diagnoses_functions.r"))

df_mitigation_constructed_6m_threshold_plot <- df_outpatient_constructed_6m_threshold_default %>%
  filter(period > ymd("2012-12-31")) %>%
  mutate(origin = "outpatient_all") %>%
  bind_rows(mutate(df_outpatient_constructed_6m_threshold_most_severe, origin = "most_severe")) %>%
  bind_rows(mutate(df_outpatient_constructed_6m_threshold_last_visit_only, origin = "final_visit")) %>%
  mutate(period = as.Date(period)) %>%
  filter(period > ymd("2019-01-01") | origin == "outpatient_all") %>%
  mutate(origin = case_when(
    origin == "outpatient_all" ~ "Unmitigated",
    origin == "final_visit" ~ "Final visit",
    origin == "most_severe" ~ "Most severe"
  ))

mitigation_constructed_6m_threshold_plot <- save_mitigation_strategy_plot(df_mitigation_constructed_6m_threshold_plot, "mitigation_constructed_6m_threshold")

mitigation_constructed_6m_threshold_plot
```



# Testing
Mitigation
```{r}
df_mitigation <- df_outpatient_constructed_default %>%
  filter(period > ymd("2012-12-31")) %>%
  mutate(origin = "outpatient_all") %>%
  bind_rows(mutate(df_outpatient_constructed_most_severe, origin = "most_severe")) %>%
  bind_rows(mutate(df_outpatient_constructed_last_visit_only, origin = "final_visit")) %>%
  mutate(period = as.Date(period)) %>%
  mutate(origin = case_when(
    origin == "outpatient_all" ~ "Unmitigated",
    origin == "final_visit" ~ "Final visit",
    origin == "most_severe" ~ "Most severe"
  ))


pacman::p_load(fable, tsibble, feasts, urca)

# Binary indicator for date in LPR2/LPR3
df_mitigation <- df_mitigation %>%
  mutate(lpr3 = if_else(period < "2019-02-03", 0, 1))


# What to report?
# pdq(0,0,0) = linear model / t.test (no detrending)
# pdq(0,1,0) = liear model with differencing
# pdq(1,1,0) = autoregressive model with differencing
df_mitigation_p_values <- df_mitigation %>%
  mutate(period = yearquarter(period)) %>%
  select(mean_2, period, origin, lpr3) %>%
  as_tsibble(key = origin, index = period) %>%
  model(arima = ARIMA(mean_2 ~ 1 + lpr3 + pdq(0, 0, 0) + PDQ(0, 0, 0))) %>%
  coef() %>%
  select(!.model) %>%
  filter(term == "lpr3") %>%
  ungroup() %>%
  mutate(
    corrected_p = p.adjust(p.value, "fdr"),
    significant = if_else(corrected_p < 0.05, "*", "")
  )


df_mitigation_p_values <- df_mitigation %>%
  filter(period == max(period)) %>%
  select(period, mean_2, origin) %>%
  left_join(df_mitigation_p_values, by = "origin")
```

```{r}
source(here("src", "individual_unique_diagnoses_functions.r"))

p <- save_mitigation_strategy_plot(df_mitigation,
  "mitigation_constructed_p_values",
  p_values = df_mitigation_p_values
)

p
```



Truncation


Hypothesis test: was there a change diagnoses during the transition?
```{r}

# binary indicator for date in LPR2/LPR3
df_truncation <- df_truncation %>%
  mutate(lpr3 = if_else(period < "2019-02-03", 0, 1))


# What to report?
# pdq(0,0,0) = linear model / t.test (no detrending)
# pdq(0,1,0) = liear model with differencing
# pdq(1,1,0) = autoregressive model with differencing
df_truncation %>%
  mutate(period = yearquarter(period)) %>%
  as_tsibble(key = truncation, index = period) %>%
  model(arima = ARIMA(mean ~ 1 + lpr3 + pdq(1, 1, 0) + PDQ(0, 0, 0))) %>%
  coef() %>%
  select(!.model)
```