---
title: "Validity of ambbesoeg"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)

p_load(
  DBI,
  data.table,
  dtplyr, 
  dplyr,
  lubridate,
  ggplot2,
  stringr,
  tidyr,
  tidyverse,
  qwraps2,
  xlsx
)

```



```{r}
conn <- DBI::dbConnect(
  odbc::odbc(),
  Driver = "SQL Server",
  Server = "BI-DPA-PROD",
  database = "USR_PS_Forsk",
  Trusted_Connection = "TRUE"
)

df_fys_raw <- dbGetQuery(conn, "SELECT * FROM [fct].FOR_besoeg_fysiske_fremmoeder") %>% 
  rename_with(tolower)

df_fys <- df_fys_raw %>% 
  select(dw_ek_borger, datotid_start)

df_tlf_raw <- dbGetQuery(conn, "SELECT * FROM [fct].FOR_telefon_video_konsultationer_psyk_somatik_LPR2") %>% 
  rename_with(tolower)

df_tlf <- df_tlf_raw %>%
  select(dw_ek_borger, datotid_udfoert) %>% 
  rename(datotid_start = datotid_udfoert)

```


Check if any "fysiske fremmoeder" are also in tlf df by dw_sk_besoeg

```{r}
df_overlap <- inner_join(df_fys, df_tlf)
```

No "visits by phone" 